# This is a basic workflow to help you get started with Actions

name: Build Tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the 075-kegman-lqr branch
on:
  push:
    branches:
      - FrogPilot_boltpilot  # Support wildcard matching
#    - comma2_Eon-final # no more comma2,,,


concurrency:
  group: ${{ github.event_name == 'push' && github.run_id || github.head_ref || github.ref }}-${{ github.workflow }}-${{ github.event_name }}
  cancel-in-progress: true






jobs:
  lint:
    # This workflow contains a single job called "build"
      name: Lint
      if: github.repository == 'jc01rho-openpilot-BoltEV2019-KoKr/FrogPilot'
      runs-on: ubuntu-20.04
      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        - uses: actions/checkout@v3
        - name: Python Linter
          uses: ricardochaves/python-lint@v1.4.0
          with:
            python-root-list: selfdrive/car/gm/** selfdrive/car/*.py selfdrive/controls/*.py
            use-pylint: true
            use-pycodestyle: false
            use-flake8: true
            use-black: false
            use-mypy: false
            use-isort: false
            extra-pylint-options: --disable=C,R,E0401,W0612,W0101,W0611,W0613,W0511,W0311,W0954,W0703,W0621,W0201,W0109,W0235,W0603,W0212,W0107,W0702,W0106
            extra-flake8-options: --select=F21,F822,F823,F831,F811,F812,E999

        - name: Python Linter
          if: always()
          uses: ricardochaves/python-lint@v1.4.0
          with:
            python-root-list: selfdrive/controls/lib/*.py
            use-pylint: true
            use-pycodestyle: false
            use-flake8: true
            use-black: false
            use-mypy: false
            use-isort: false
            extra-pylint-options: --disable=C,R,E0401,W0612,W0101,W0611,W0613,W0511,W0311,W0954,W0703,W0621,W0201,W0109,W0235,W0603,W0106,W0107,W0702,W0212,W0105,W0128,W0125
            extra-flake8-options: --select=F21,F822,F823,F831,F811,F812,E999
